--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KienMCVN/FixItemUI
build-by-default: true
branches:
- main
projects:
  FixItemUI:
    path: ""
    icon: holding-wrench.png
    libs:
    - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy 
      version: ^3.0.2
...
