--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KienMCVN/FixItemUI-V0.0.1
build-by-default: true
branches:
- main
projects:
  FixItemUI-V0.0.1:
    path: ""
    libs:
    - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy 
      version: ^3.0.2
...
