name: FixItemUI
main: FixItem\KienMC\Main
api: 5.0.0
version: 0.0.1
author:
- Kiên MC
description: Plugin Fix Item Code By Kiên MC
virions:
- libPiggyEconomy
commands:
   fixitem:
      description: "Open Menu Fix Item"
      permission: fixitem.cmd
   fix:
      description: "Fix Item"
      permission: fix.cmd
   fixall:
      description: "Fix All Item"
      permission: fixall.cmd
permissions:
   fixitem.cmd:
      default: true
   fix.cmd:
      default: op
   fixall.cmd:
      default: op
